version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
  build:
    commands:
      - dotnet restore
      - dotnet build
      - echo Build finished on `date`
      - dotnet publish -o build-site
      - dir
      - cd GitCICDDemo/build-site
      - echo dir in GitCICDDemo/build-site
      - dir
      - echo dir in wwwroot
      - dir wwwroot
      - zip -r ../../site.zip *
      - echo Zip to site.zip finished on `date`
artifacts:
  files:
    - site.zip
    - aws-windows-deployment-manifest.json