version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
  build:
    commands:
      - dotnet restore
      - dotnet build
artifacts:
  files:
    - GitCICDDemo/build_output/**/*
    - scripts/**/*