version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
  build:
    commands:
      - dotnet restore
      - dotnet build
      - echo Build finished on `date`
      - dotnet publish -c release -o GitCICDDemo/build_output
      - zip site.zip GitCICDDemo/build_output
      
artifacts:
  files:
    - TESTApp.zip
    - aws-windows-deployment-manifest.json